#!/usr/bin/env node
/**
 * validate-blocks.cjs — pinned block validator / normalizer / lint (inner-loop tier).
 *
 * Three SEPARATE outcomes (PLAN.md, re-scoped 2026-06-11):
 *   1. INVALID  — @wordpress/blocks parse() says the saved markup doesn't match save()
 *                 (the class of error that breaks the editor while the frontend renders fine).
 *   2. NORMALIZE — parse() succeeded but createBlock()+serialize() emits different markup
 *                 (deprecated-but-migrated attribute forms). WARNING ONLY, with a diff hint —
 *                 not invalid; the site's editor may be older than these packages.
 *   3. LINT     — outside Gutenberg validation: core/missing, core/freeform, raw <style> tags,
 *                 block types unknown to the core registry (plugin blocks are INVISIBLE here —
 *                 the Playwright editor gate is the final authority).
 *
 * Usage:  node validate-blocks.cjs <file.html> [...]     (block markup files: templates/parts)
 *         node validate-blocks.cjs --self-check          (three-sample gate; run before any
 *                                                         version bump and in CI)
 * Exit: 0 = no INVALID and no LINT (NORMALIZE warnings allowed); 1 otherwise.
 *
 * CommonJS + pinned versions + these exact shims are load-bearing: latest ESM fails on Node 22
 * JSON imports, and the wp-6.9 dist-tag set crashes outright (nested duplicate @wordpress/blocks,
 * MutationObserver shim, block-editor hook TypeError — all verified 2026-06-11).
 * Core blocks only (registerCoreBlocks). Validates against the PINNED packages, not the site's
 * WP version. Run it before declaring a template done; run the editor gate before deploy.
 */

'use strict';

/* ---- jsdom shims (must precede any @wordpress import; list from the verified set) ---- */
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>', {
  url: 'http://localhost',
  pretendToBeVisual: true,
});
global.window = dom.window;
global.document = dom.window.document;
global.DOMParser = dom.window.DOMParser;
global.XMLSerializer = dom.window.XMLSerializer;
global.Node = dom.window.Node;
global.Element = dom.window.Element;
global.HTMLElement = dom.window.HTMLElement;
global.getComputedStyle = dom.window.getComputedStyle;
global.MutationObserver = dom.window.MutationObserver;
global.CSS = { escape: (s) => s.replace(/[^a-zA-Z0-9_-]/g, (c) => `\\${c}`), supports: () => false };
global.requestAnimationFrame = (cb) => setTimeout(cb, 16);
global.cancelAnimationFrame = (id) => clearTimeout(id);
global.matchMedia = () => ({
  matches: false,
  addListener: () => {},
  removeListener: () => {},
  addEventListener: () => {},
  removeEventListener: () => {},
});
global.ResizeObserver = class { observe() {} unobserve() {} disconnect() {} };
if (!global.navigator) {
  Object.defineProperty(global, 'navigator', {
    value: { userAgent: 'node', platform: 'node' },
    configurable: true,
  });
}

/* Gutenberg logs every validation failure as a multi-screen console dump; keep our output
 * readable. The findings carry the one-line reason from validationIssues instead. */
for (const m of ['log', 'info', 'warn', 'error', 'group', 'groupCollapsed', 'groupEnd']) {
  const orig = console[m].bind(console);
  console[m] = (...a) => {
    const s = String(a[0] ?? '');
    if (s.startsWith('Block validation:') || s.startsWith('Content generated by') || s.includes('Could not parse CSS')) return;
    orig(...a);
  };
}

const { parse, serialize, registerCoreBlocks } = (() => {
  const blocks = require('@wordpress/blocks');
  const { registerCoreBlocks } = require('@wordpress/block-library');
  return { ...blocks, registerCoreBlocks };
})();

registerCoreBlocks();

/* ---------------------------------- checks ---------------------------------- */

function flatten(blockList, out = []) {
  for (const b of blockList) {
    out.push(b);
    if (b.innerBlocks && b.innerBlocks.length) flatten(b.innerBlocks, out);
  }
  return out;
}

function checkMarkup(label, markup) {
  const findings = { invalid: [], normalize: [], lint: [] };

  // LINT: raw <style> outside block comments (Telex rule: never in templates/patterns)
  if (/<style[\s>]/i.test(markup)) {
    findings.lint.push(`${label}: raw <style> tag in markup`);
  }

  const parsed = parse(markup);
  const flat = flatten(parsed);

  for (const b of flat) {
    if (b.name === 'core/missing') {
      findings.lint.push(`${label}: core/missing (unrecognized content${b.attributes && b.attributes.originalName ? `: ${b.attributes.originalName}` : ''})`);
      continue;
    }
    if (b.name === 'core/freeform') {
      findings.lint.push(`${label}: core/freeform (classic/unstructured content)`);
      continue;
    }
    if (b.isValid === false) {
      const why = (b.validationIssues || [])
        .map((i) => (i && i.args ? String(i.args[0]) : ''))
        .filter(Boolean)
        .slice(0, 1);
      findings.invalid.push(`${label}: ${b.name}${why.length ? ` — ${why[0]}` : ''}`);
    }
  }

  // NORMALIZE: parse() migrates deprecated forms, so serialize(parse(src)) is the canonical
  // markup — compare it against what was actually WRITTEN. (Comparing a createBlock round-trip
  // against serialize(parsed) is a no-op: both sides are already migrated — caught by the
  // self-check on first run.) Only meaningful when nothing is invalid.
  if (findings.invalid.length === 0 && findings.lint.length === 0) {
    try {
      const canonical = serialize(parsed);
      if (normalizeWs(canonical) !== normalizeWs(markup)) {
        findings.normalize.push(`${label}: markup differs from canonical serialize(parse()) — deprecated form migrated (warning, not invalid; the site's editor may still accept the original)`);
      }
    } catch (e) {
      findings.normalize.push(`${label}: normalization round-trip failed (${e.message})`);
    }
  }

  return findings;
}

function normalizeWs(s) {
  return s.replace(/\s+/g, ' ').trim();
}

/* -------------------------------- self-check -------------------------------- */
/* Three samples, one per outcome. ALL THREE must report exactly their own outcome
 * or the pinned set is broken — run before any version bump. */

const SAMPLES = {
  invalid: `<!-- wp:cover {"dimRatio":50} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-50 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph -->
<p>Stale Telex cover example</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->`,
  normalize: `<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Old-style centered paragraph</p>
<!-- /wp:paragraph -->`,
  lint: `<!-- wp:paragraph -->
<p>Hello</p>
<!-- /wp:paragraph -->

<style>.x{color:red}</style>`,
};

function selfCheck() {
  let ok = true;
  const expect = (cond, msg) => {
    console.log(`${cond ? 'PASS' : 'FAIL'}: ${msg}`);
    if (!cond) ok = false;
  };

  const inv = checkMarkup('sample:invalid', SAMPLES.invalid);
  expect(inv.invalid.length > 0, 'invalid sample reports INVALID (cover dimRatio-50)');

  const norm = checkMarkup('sample:normalize', SAMPLES.normalize);
  expect(norm.invalid.length === 0, 'normalize sample is NOT invalid');
  expect(norm.normalize.length > 0, 'normalize sample reports NORMALIZE diff');

  const lint = checkMarkup('sample:lint', SAMPLES.lint);
  expect(lint.invalid.length === 0, 'lint sample is NOT invalid');
  expect(lint.lint.length > 0, 'lint sample reports LINT (raw <style>/core-missing)');

  console.log(ok ? 'SELF-CHECK PASS — pinned set is sane' : 'SELF-CHECK FAIL — do not use or bump this set');
  process.exit(ok ? 0 : 1);
}

/* ----------------------------------- main ----------------------------------- */

const args = process.argv.slice(2);
if (args[0] === '--self-check') selfCheck();
if (args.length === 0) {
  console.error('usage: node validate-blocks.cjs <file.html> [...] | --self-check');
  process.exit(1);
}

const fs = require('fs');
let invalidCount = 0;
let lintCount = 0;
for (const f of args) {
  const r = checkMarkup(f, fs.readFileSync(f, 'utf8'));
  for (const m of r.invalid) console.log(`INVALID   ${m}`);
  for (const m of r.lint) console.log(`LINT      ${m}`);
  for (const m of r.normalize) console.log(`NORMALIZE ${m}`);
  invalidCount += r.invalid.length;
  lintCount += r.lint.length;
}
console.log(
  invalidCount + lintCount === 0
    ? 'OK (normalization warnings, if any, are non-fatal)'
    : `FAIL: ${invalidCount} invalid, ${lintCount} lint`
);
process.exit(invalidCount + lintCount === 0 ? 0 : 1);
