<?php
/**
 * Content loader — self-registers theme pages from files, idempotently.
 *
 * Drop this file in the theme root and `require_once` it from functions.php (scaffold-theme.sh
 * does both). It scans `content/pages/*.html` and inserts/updates one published Page per file —
 * so page content stays editable as files AND lives in the database, with no per-build
 * `wp_insert_post` loop, no temp setup PHP, and no manual `show_on_front` wiring. It also promotes
 * a `home` page to the static front page automatically (the front-page bug-class: setting
 * `show_on_front=page` without `page_on_front`).
 *
 * One file per page: the filename (minus `.html`) is the slug; the body is block markup. The page
 * title comes from an optional leading `<!-- title: My Title -->` comment, else the humanized slug.
 *
 * Idempotent: re-running updates a page only when the file content changed (tracked via a content
 * hash in post meta), so it can safely run on every `init` during local development — edit a file,
 * reload, the page updates. Do not edit this file inside a generated theme.
 *
 * @package theme-boilerplate
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'theme_content_loader_run' ) ) {

	/**
	 * Insert/update all theme pages from content/pages/*.html, then set the front page.
	 */
	function theme_content_loader_run() {
		$dir = get_theme_file_path( 'content/pages' );
		if ( ! is_dir( $dir ) ) {
			return;
		}

		$files = glob( trailingslashit( $dir ) . '*.html' );
		if ( empty( $files ) ) {
			return;
		}

		$home_id = 0;

		foreach ( $files as $file ) {
			$slug = sanitize_title( basename( $file, '.html' ) );
			if ( '' === $slug ) {
				continue;
			}

			$raw = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions
			if ( false === $raw ) {
				continue;
			}

			// Optional leading `<!-- title: ... -->` header; otherwise humanize the slug.
			$title = ucwords( str_replace( array( '-', '_' ), ' ', $slug ) );
			$body  = $raw;
			if ( preg_match( '/^\s*<!--\s*title:\s*(.+?)\s*-->\s*/i', $raw, $m ) ) {
				$title = trim( $m[1] );
				$body  = substr( $raw, strlen( $m[0] ) );
			}

			$hash     = md5( $title . '|' . $body );
			$existing = get_page_by_path( $slug, OBJECT, 'page' );

			if ( $existing instanceof WP_Post ) {
				$post_id = (int) $existing->ID;
				// Skip the write when nothing changed.
				if ( get_post_meta( $post_id, '_theme_content_hash', true ) !== $hash ) {
					wp_update_post(
						array(
							'ID'           => $post_id,
							'post_title'   => $title,
							'post_content' => $body,
						)
					);
					update_post_meta( $post_id, '_theme_content_hash', $hash );
				}
			} else {
				$post_id = wp_insert_post(
					array(
						'post_title'   => $title,
						'post_name'    => $slug,
						'post_content' => $body,
						'post_status'  => 'publish',
						'post_type'    => 'page',
					)
				);
				if ( $post_id && ! is_wp_error( $post_id ) ) {
					update_post_meta( $post_id, '_theme_content_hash', $hash );
				}
			}

			if ( 'home' === $slug && $post_id && ! is_wp_error( $post_id ) ) {
				$home_id = (int) $post_id;
			}
		}

		// Promote the home page to the static front page (both options, together).
		if ( $home_id > 0 && (int) get_option( 'page_on_front' ) !== $home_id ) {
			update_option( 'show_on_front', 'page' );
			update_option( 'page_on_front', $home_id );
		}
	}

	// Priority 99: after CPTs registered at the default init priority, so CPT-bound content (if any
	// is added later) finds its types registered.
	add_action( 'init', 'theme_content_loader_run', 99 );
}
