#!/usr/bin/env node
/*
 * fix-blocks.cjs — programmatically repair WordPress block-validity errors in template / part /
 * pattern / content files, WITHOUT loading them in a browser editor.
 *
 *   node fix-blocks.cjs <file...> [--dry]
 *
 * How it works (the same trick Telex's block-fixer uses): register core blocks in jsdom, parse()
 * the markup, then recreate EVERY block from its parsed attributes via createBlock() and
 * serialize() it back. createBlock() regenerates exactly what WordPress save() produces — correct
 * element order, canonical class names (has-background-dim, not has-background-dim-50), required
 * empty alt="" on cover background images, CSS property order, dropped unknown attributes — so the
 * structural mismatches that make a block "invalid" in the editor are normalized away. This fixes
 * the cases the editor gate would otherwise flag, in milliseconds, with no live site.
 *
 * Run it right after writing/editing templates, parts, and patterns, then run validate-blocks.cjs
 * to confirm. Files are rewritten in place (use --dry to preview which files would change).
 *
 * Scope: it rebuilds named core blocks from attributes. Freeform/HTML blocks (wp:html, raw markup
 * with no block name) are left untouched. Pattern PHP headers (everything up to `?>`) are
 * preserved; only the block markup after them is fixed.
 *
 * Deps are the checker's own (@wordpress/blocks, @wordpress/block-library, jsdom) — run
 * `npm install` in scripts/checker/ once, same as the other gates.
 */
'use strict';

/* ---- jsdom shims (must precede any @wordpress import; mirrors validate-blocks.cjs) ---- */
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>', {
  url: 'http://localhost',
  pretendToBeVisual: true,
});
global.window = dom.window;
global.document = dom.window.document;
global.DOMParser = dom.window.DOMParser;
global.XMLSerializer = dom.window.XMLSerializer;
global.Node = dom.window.Node;
global.Element = dom.window.Element;
global.HTMLElement = dom.window.HTMLElement;
global.getComputedStyle = dom.window.getComputedStyle;
global.MutationObserver = dom.window.MutationObserver;
global.CSS = { escape: (s) => s.replace(/[^a-zA-Z0-9_-]/g, (c) => `\\${c}`), supports: () => false };
global.requestAnimationFrame = (cb) => setTimeout(cb, 16);
global.cancelAnimationFrame = (id) => clearTimeout(id);
global.matchMedia = () => ({ matches: false, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {} });
global.ResizeObserver = class { observe() {} unobserve() {} disconnect() {} };
if (!global.navigator) {
  Object.defineProperty(global, 'navigator', { value: { userAgent: 'node', platform: 'node' }, configurable: true });
}

/* Gutenberg dumps every validation failure to the console; silence the noise. */
for (const m of ['log', 'info', 'warn', 'error', 'group', 'groupCollapsed', 'groupEnd']) {
  const orig = console[m].bind(console);
  console[m] = (...a) => {
    const s = String(a[0] ?? '');
    if (s.startsWith('Block validation:') || s.startsWith('Content generated by') || s.includes('Could not parse CSS')
      || s.startsWith('Updated Block') || s.startsWith('Block successfully updated')
      || s.startsWith('New content generated') || s.startsWith('Content retrieved from')) return;
    orig(...a);
  };
}

const { parse, serialize, createBlock, registerCoreBlocks } = (() => {
  const blocks = require('@wordpress/blocks');
  const { registerCoreBlocks } = require('@wordpress/block-library');
  return { ...blocks, registerCoreBlocks };
})();
registerCoreBlocks();

/* ---------------------------- nested-<p> repair ----------------------------
 * serialize() can wrap mismatched paragraph content in a second <p>; collapse nested
 * <p><p>…</p></p> back to one, merging class/style. (Ported from Telex's paragraphFixer.) */
function parseAttrs(s) {
  const a = {}; if (!s) return a;
  for (const re of [/(\S+)="([^"]*)"/g, /(\S+)='([^']*)'/g]) {
    let m; while ((m = re.exec(s)) !== null) if (!(m[1] in a)) a[m[1]] = m[2];
  }
  return a;
}
function mergeAttrs(outer, inner) {
  const o = parseAttrs(outer), i = parseAttrs(inner), merged = { ...o };
  for (const [k, v] of Object.entries(i)) {
    if (k === 'class') {
      merged.class = [...new Set([...(o.class || '').split(/\s+/), ...v.split(/\s+/)].filter(Boolean))].join(' ');
    } else if (k === 'style') {
      const map = {};
      for (const decl of [...(o.style || '').split(';'), ...v.split(';')]) {
        const c = decl.indexOf(':'); if (c > 0) map[decl.slice(0, c).trim()] = decl.slice(c + 1).trim();
      }
      merged.style = Object.entries(map).map(([p, val]) => `${p}:${val}`).join(';');
    } else if (!(k in merged)) merged[k] = v;
  }
  return merged;
}
function fixNestedParagraphs(html) {
  if (!html.includes('<!-- wp:paragraph')) return html;
  const block = /(<!-- wp:paragraph[^>]*-->)([\s\S]*?)(<!-- \/wp:paragraph -->)/g;
  const nested = /<p(\s[^>]*)?>(\s*)<p(\s[^>]*)?>([^]*?)<\/p>(\s*)<\/p>/gi;
  return html.replace(block, (_m, open, content, close) => {
    let cur = content, prev;
    do {
      prev = cur;
      cur = cur.replace(nested, (_x, oa, _w1, ia, inner) => {
        const merged = mergeAttrs(oa, ia);
        const attr = Object.entries(merged).map(([k, v]) => ` ${k}="${v}"`).join('');
        return `<p${attr}>${inner}</p>`;
      });
    } while (cur !== prev);
    return `${open}${cur}${close}`;
  });
}

/* ---------------------------- block re-creation ---------------------------- */
function rebuild(block) {
  const inner = (block.innerBlocks || []).map(rebuild);
  // Freeform / nameless (raw HTML, wp:html) — leave exactly as-is.
  if (!block.name) return block;
  return createBlock(block.name, block.attributes, inner.length ? inner : undefined);
}

// Inline PHP (e.g. src="<?php echo esc_url( get_theme_file_uri('assets/x.png') ); ?>" in a cover
// url/img) can't survive parse()→serialize() — the serializer HTML-escapes `<?php`. So mask every
// <?php…?> span with an inert alnum sentinel before parsing, then restore the originals after. The
// sentinel is a valid attribute value (and plain text), so it round-trips through createBlock →
// serialize unchanged; the cover's save() even carries the url sentinel into the regenerated <img
// src>. This is what lets fix-blocks repair covers/groups in PHP patterns instead of the agent
// hand-fixing them via canonicalize.
// The sentinel must be a value that's VALID wherever the PHP sat — these spans are almost always a
// cover url / img src, and a cover validates its url, so a non-URL token (e.g. a bare word) makes
// the cover parse as invalid and produces false "needs hand fix" noise on otherwise-valid covers.
// A URL-shaped sentinel is treated as a normal image URL and round-trips cleanly.
function maskPhp(html) {
  const spans = [];
  const masked = html.replace(/<\?php[\s\S]*?\?>/g, (m) => {
    const token = 'https://php-sentinel.invalid/' + spans.length;
    spans.push(m);
    return token;
  });
  return { masked, spans };
}
function unmaskPhp(html, spans) {
  return html.replace(/https:\/\/php-sentinel\.invalid\/(\d+)/g, (_, i) => spans[+i] ?? _);
}

function fixMarkup(html) {
  const { masked, spans } = maskPhp(html);
  const pre = fixNestedParagraphs(masked);
  const parsed = parse(pre);
  const issues = [];
  const collect = (list) => list.forEach((b) => {
    if (b.isValid === false) issues.push(b.name || 'unknown');
    if (b.innerBlocks) collect(b.innerBlocks);
  });
  collect(parsed);
  let out = serialize(parsed.map(rebuild));
  out = fixNestedParagraphs(out);
  out = unmaskPhp(out, spans);
  return { html: out, changed: out !== html, invalid: [...new Set(issues)] };
}

/* ------------------------------- file handling ------------------------------- */
const fs = require('fs');

// Pattern PHP: preserve the header up to and including `?>`, fix only the markup after it.
function splitPattern(content) {
  const i = content.indexOf('?>');
  return i === -1 ? null : { header: content.slice(0, i + 2), body: content.slice(i + 2) };
}

function fixFile(path, dry) {
  let content;
  try { content = fs.readFileSync(path, 'utf8'); }
  catch (e) { console.log(`SKIP   ${path} — ${e.message}`); return false; }
  if (!content.includes('<!-- wp:')) { console.log(`skip   ${path} — no block markup`); return false; }

  let result, rewrite;
  if (path.endsWith('.php')) {
    const parts = splitPattern(content);
    if (!parts) { console.log(`skip   ${path} — no closing ?> before markup`); return false; }
    // Inline <?php…?> in the block markup is masked/restored inside fixMarkup, so covers/groups in
    // PHP patterns are auto-repaired like any other file.
    result = fixMarkup(parts.body);
    rewrite = parts.header + result.html;
  } else {
    result = fixMarkup(content);
    rewrite = result.html;
  }

  // Rewrite ONLY when there's a genuine INVALID block AND re-serialize actually changed the markup.
  // Everything else is `ok`:
  //  - no invalid  → don't touch it (re-serializing valid markup would churn it to the pinned
  //    @wordpress/blocks form — textAlign→style, separator opacity — possibly diverging from the
  //    live WP; the editor gate is the authority for valid markup).
  //  - invalid but unchanged → the markup is already createBlock-canonical and fix-blocks can't
  //    improve it; the pinned "invalid" is unreliable for the live site (the pinned parser lags
  //    the running WP, so covers/groups the live editor accepts can re-parse invalid here). Report
  //    ok and let the editor gate decide — never tell the agent to "hand fix"; that loop is what
  //    this script replaces.
  if (!result.invalid.length || !result.changed) { console.log(`ok     ${path}`); return false; }
  const tag = ` (was invalid: ${result.invalid.join(', ')})`;
  if (dry) { console.log(`WOULD-FIX ${path}${tag}`); return true; }
  try { fs.writeFileSync(path, rewrite); } catch (e) { console.log(`SKIP   ${path} — write failed: ${e.message}`); return false; }
  console.log(`FIXED  ${path}${tag}`);
  return true;
}

const argv = process.argv.slice(2);
const dry = argv.includes('--dry');
const files = argv.filter((a) => !a.startsWith('--'));
if (!files.length) {
  console.error('Usage: fix-blocks.cjs <file...> [--dry]\n  Fixes templates/parts (.html) and patterns/content (.php/.html) in place.');
  process.exit(2);
}
let changed = 0;
for (const f of files) { try { if (fixFile(f, dry)) changed++; } catch (e) { console.log(`ERROR  ${f} — ${e.message}`); } }
console.log(dry
  ? `\n${changed} file(s) would change. Re-run without --dry to apply, then validate-blocks.cjs to confirm.`
  : `\n${changed} file(s) rewritten. Run validate-blocks.cjs on them to confirm.`);
